FROM python:3.9-slim
RUN apt update
RUN apt install -y build-essential
COPY docker/main/requirements.txt /app/requirements.txt
COPY server.py /app/server.py
WORKDIR /app
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r requirements.txt
ENTRYPOINT ["python3", "server.py"]