version: "3"
services:
    main:
        build:
            dockerfile: docker/main/dockerfile
            context: ..
        container_name: minaa
        restart: no
        volumes:
            - ../web:/app/web
        ports:
            - 127.0.0.1:8000:8000
        networks:
            - app_network
networks:
    app_network:
        driver: bridge
